-- Generated by skardi-etl. Idempotent: plain re-apply is a no-op;
-- `skardi-etl setup --reset` drops these artifacts first (the v1
-- rebuild path).
--
-- doc_id is deliberately NOT a primary key: jobs are append-only
-- (no ON CONFLICT path in the executor), so a unique constraint
-- would hard-fail {since} replay mid-stream. Replay accumulates
-- rows; the search pipeline deduplicates by doc_id at read time,
-- and the PRIMARY KEY arrives with v2 upsert. `rid` is the
-- INTEGER rowid alias the vec0 mirror requires (and the join key
-- the pipelines use); SQLite assigns it on the NULL the ingest
-- SELECT emits.
CREATE TABLE IF NOT EXISTS documents (
  rid INTEGER PRIMARY KEY,
  doc_id TEXT NOT NULL,
  source_table TEXT NOT NULL,
  source_id TEXT NOT NULL,
  title TEXT,
  content TEXT NOT NULL,
  chunk_index INTEGER NOT NULL,
  author TEXT,
  created_at TEXT,
  metadata TEXT,
  embedding BLOB NOT NULL
);

-- Text arm: standalone fts5 mirror (rebuild-first keeps triggers
-- insert-only).
CREATE VIRTUAL TABLE IF NOT EXISTS documents_fts USING fts5(
  content,
  doc_rowid UNINDEXED
);

-- Vector arm: vec0 requires the INTEGER key.
CREATE VIRTUAL TABLE IF NOT EXISTS documents_vec USING vec0(
  doc_rowid INTEGER PRIMARY KEY,
  embedding float[384]
);

-- Sync triggers: INSERT-only by design (append-only jobs;
-- rebuild-first refresh). NEW.rid carries the join key.
CREATE TRIGGER IF NOT EXISTS documents_ai_fts
AFTER INSERT ON documents BEGIN
  INSERT INTO documents_fts(doc_rowid, content)
  VALUES (NEW.rid, NEW.content);
END;

CREATE TRIGGER IF NOT EXISTS documents_ai_vec
AFTER INSERT ON documents BEGIN
  INSERT INTO documents_vec(doc_rowid, embedding)
  VALUES (NEW.rid, NEW.embedding);
END;
