[package]
name = "model"
version.workspace = true
edition.workspace = true
description.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true

[features]
default = []
onnx = ["dep:ort", "dep:ndarray", "dep:num_cpus"]

[dependencies]
anyhow = { workspace = true  }
arrow = { workspace = true  }
datafusion = { workspace = true }
log = { workspace = true }
ndarray = { version = "0.17", optional = true }
num_cpus = { version = "1.17.0", optional = true }
ort = { version = "2.0.0-rc.12", default-features = false, features = ["std", "ndarray", "download-binaries", "tls-rustls"], optional = true }
tokio = {workspace = true,  features = ["macros", "rt-multi-thread", "sync"]}
tracing = { workspace = true }

[dev-dependencies]
sources = { path = "../sources" }

[lints]
workspace = true
